TestProject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from TestProject import settings, views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^angular/$', TemplateView.as_view(template_name='test-angular.html')),
    url(r'^admin/', admin.site.urls),
    url(r'^reddit/', include('reddit.urls', namespace='reddit')),
    url(r'^login/$',auth_views.login),
    url(
        r'^logout/$',
        auth_views.logout,
        name='logout',
        kwargs={
            'next_page': settings.LOGIN_URL,
        }
    ),

]

reddit/urls.py
from django.conf.urls import url
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    url(r'^$', RedirectView.as_view(pattern_name='reddit:index')),
    url(r'^index/$', views.index, name='index'),
    url(r'^add/$', views.addPost, name='addPost'),
    url(r'^(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<pk>[0-9]+)/rate/$', views.ratePost, name='ratePost'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.deletePost, name='deletePost'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.editPost, name='editPost'),
    url(r'^(?P<pk>[0-9]+)/comment/$', views.addComment, name='addComment'),
    url(r'^comment/(?P<pk>[0-9]+)/edit/$', views.editComment, name='editComment'),
    url(r'^comment/(?P<pk>[0-9]+)/delete/$', views.deleteComment, name='deleteComment'),
    url(r'^comment/(?P<pk>[0-9]+)/reply/$', views.addReply, name='addReply'),
]

templates/add_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add New Post</title>
</head>
<body>
<form action="{% url 'reddit:addPost' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Reddit Style Test{% endblock %}</title>
    <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<script type="text/javascript" src="{% static "angular.min.js"%}"></script>
      <script type="text/javascript" src="{% static "js/testCtrl.js" %}"></script>

    <style>
        .voted{
            background-color: cornflowerblue;
            color: white;
        }
        .post-wrapper{
            border: 1px solid ghostwhite;
            border-radius: 3px;
            padding: 16px;
        }
        button{
            outline: 0;
            background: none;
            border: 0;
        }

        button, a {
            color: slateblue;
            font-size: 16px;
            text-decoration: none;
            padding: 0;
            margin: 0;
        }

        a > span{
            color: black;
        }

        #content {
            margin:auto;
            width: 100%;
            max-width: 800px;
        }

        .comment {
            border: 1px solid cornflowerblue;
            margin: 2px;
        }

        .reply {
            padding-left: 30px;
        }

        .hidden{
            display: none;
        }

        .up, .down {
            padding:3px;
            border-radius: 3px;
        }
        .pressed{
            background-color: gray;
        }


        .truncate {
          white-space: nowrap;
          overflow: hidden;
          text-overflow: ellipsis;
        }
        .new, .hot{
            margin-right: 5px;
        }
        .new {
            color:dodgerblue;
        }

        .hot{
            color:red;
        }

        .hide{
            display: none;
        }
    </style>
</head>
<body>
    <div id="sidebar">
    <ul>
        <li><a href="/">Home</a></li>
        <li><a href="/reddit">Reddit</a></li>
    </ul>
    {% if user.is_authenticated%}로그인된 유저 : {{ request.user.username }} <a href="/logout">로그아웃</a>
    {% else %}
        로그인되지 않음 <a href="/login/">로그인</a>
    {% endif %}
        {% block sidebar %}{% endblock %}
    </div>
    <div id="content" ng-app="myApp">
        {% block content %}{% endblock %}
    </div>
</body>
<script>
// using jQuery
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});
{% block script %}{% endblock %}
{% if alert %}
        alert('{{ alert }}');
    {% endif %}</script>
</html>

templates/post_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Add New Post</title>
</head>
<body>
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
</body>
</html>

templates/post_detail.html
{% extends "base.html" %}
{% load reddit_extra %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <script>window.csrf_token = '{{ csrf_token }}';</script>
     <div id="example" ng-controller="myCtrl" ng-init="init({{ comment_list }})">
        <div ng-repeat="c in comments" ng-click="hide(c)">
            <my-directive comment="c"></my-directive>
        </div>

    <h1>{{ post.title }}</h1>
    <div id="post-info">
        <span>{{ post.created_by.username }}</span>
        <span>{{ post.pub_date | custom_time}}</span>
        <span>추천수 : {{ post.vote_sum }}</span>
    </div>
    <div id="post-content">
    <h3>내용 : </h3>
    {{ post.content | linebreaks }}
    <br><br>
    </div>
    {% if request.user == post.created_by %}
        <form action="{% url 'reddit:deletePost' post.id %}" method="post">
            {% csrf_token %}
            <button type=submit id="delete">삭제하기</button>
        </form>
        <a href="{% url 'reddit:editPost' post.id %}">수정하기</a>
    {% endif %}

    <div id="comments">
        <h3>댓글 : </h3>
        {% for comment in post.comments.all %}
            <div class="comment" value="{{ comment.id }}">
            {{ comment.content | linebreaks }} - {{ comment.commented_by.username }}, {{ comment.created_at | custom_time}}
            <button class="add-reply-btn" value="{{ comment.id }}">댓글달기</button>
            <button class="show-reply-btn">대댓보기</button>
                <div class="replies hidden">
                {% for reply in comment.replies.all %}
                    <div class="comment reply">
                    ㄴ {{ reply.content | linebreaks }} - {{ reply.commented_by.username }}, {{ reply.created_at | custom_time}}
                    </div>
                {% endfor %}
            </div>

            </div>
        {% endfor %}
    </div>
    <div id="new_comment">
        <form action="" value="{% url 'reddit:addComment' post.id %}" method="post" ng-submit="submit('{% url 'reddit:addComment' post.id %}')" onsubmit="event.preventDefault(); return false;">
            {% csrf_token %}
            {{ comment_form }}
           <button type="submit">확인</button>
        </form>
    </div>
    <a href="{% url 'reddit:index' %}">돌아가</a>
     </div>
{% endblock %}

{% block script %}

    $('#delete').click(function(e){
        if(!confirm('삭제?')){
            e.preventDefault()
        }
    });
    form = ""
    $(document).ready(
        function(){
    {% spaceless %}
        form = '<form method="post">'
        +"{% csrf_token %}"
        +'<input type="hidden" name="redirect" value="'
        +window.location.href+'">'+'{{ comment_form }}'+'<button type="submit">확인</button></form>';
    {% endspaceless %}
    });

    $('.add-reply-btn').click(
        function(e){
            console.log($(this).parent().has('.add-reply'));
            if($(this).parent().has('.add-reply').length != 0){
                $(this).parent().children().remove('.add-reply');
            } else {
                var comment_id = $(this).val();
                var url = '{% url 'reddit:addReply' 99999 %}'.replace(99999, comment_id);
                $('<div/>', {class:'add-reply'}).append(form).appendTo($(this).parent());
                $(this).parent().find('form').attr('action',url);

{#    form 리스너 반복#}
                $('form').submit(function(e){
                e.preventDefault();
                console.log($(this).serialize());
                console.log($(this).attr('value'));
                $.post($(this).attr('action'), $(this).serialize(), function(data){
                    console.log(data);
                });
        return false;
    });
            }
        }
    );

    $('.show-reply-btn').click(
        function(){
            console.log('showreply clicked');
            var replies_div = $(this).parent().find('.replies');

            console.log(replies_div);
            console.log(replies_div.hasClass('hidden'));
            if(replies_div.hasClass('hidden')){
                replies_div.removeClass('hidden');
            } else {
                replies_div.addClass('hidden');
            }
    });

{#    $('form').submit(function(e){#}
{#        e.preventDefault();#}
{#        console.log($(this).serialize());#}
{#        console.log($(this).attr('value'));#}
{#        $.post($(this).attr('action'), $(this).serialize(), function(data){#}
{#            console.log(data);#}
{#        });#}
{#    {$ doAngular() $}#}
{#        return false;#}
{#    });#}


{% endblock %}

templates/post_edit.html
{% extends 'base.html' %}

{% block title %}포스트 수정{% endblock %}

{% block content %}
    <form action="{% url 'reddit:editPost' post.id%}" method="post">
    {% csrf_token %}
    {{ form }}
    <button type="submit">수정하기</button>
    </form>
{% endblock %}

templates/post_list.html
{% extends "base.html" %}
{% load reddit_extra %}
{% block title %}글목록{% endblock %}

{% block content %}
<a href="{% url 'reddit:addPost' %}">새글쓰기</a>
    {% for post in posts %}
        <div class="post-wrapper">
            <a href="{% url 'reddit:detail' pk=post.id %}">
                <span class="truncate">{{ post.title }} </span>{% if post.pub_date|check_new %}<span class="new">NEW</span>{% endif %}{% if post.vote_sum|check_hot %}<span class="hot">HOT</span>{% endif %}
            </a>
            <p>추천수 : {{ post.vote_sum }} / 작성자 : {{ post.created_by.username }} / 작성시간 : {{ post.pub_date|custom_time }}</p>
            <form>
                <button value="{{ post.id }}" class="up{% if post|up_voted_by:request.user %} voted{% endif %}">Up</button>
                <button value="{{ post.id }}" class="down{% if post|down_voted_by:request.user %} voted{% endif %}">Down</button>
            </form>
        </div>
    {% endfor %}
{% endblock %}

{% block script %}
    $('.up').click(
        function(){
            pk = $(this).val();
            if($(this).hasClass('voted')){
                delete_vote(pk);
            }
            else {
                up_vote(pk);
            }
        }
    );
    $('.down').click(
        function(){
            pk = $(this).val();
            if($(this).hasClass('voted')){
                delete_vote(pk);
            }
            else {
                down_vote(pk);
            }
        }
    );

    function up_vote(pk){
        vote(pk,1);
    }
    function down_vote(pk){
        vote(pk,-1);
    }
    function delete_vote(pk){
        vote(pk,0);
    }
    function vote(pk,val){
        {% if request.user.is_authenticated %}
        $.post('../'+pk+'/rate/', {'val':val},'json');
        {% else %}
            alert('x');
        {% endif %}
    }
{% endblock %}

templates/test-angular.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <title>Hello AngularJS!</title>
       <script>

    </script>
  </head>
  <body ng-app="myApp">
    <div id="example" ng-controller="myCtrl">
        <div ng-repeat="c in comment">
            <my-directive comment="c"></my-directive>
        </div>
    </div>
  </body>
</html>